package com.amrilhakimsihotang.submissionarchitecturecomponent.local

object DummyMovies {

 val personcasting = arrayOf(
            "Nicolas Cage, Alain Moussi, Frank Grillo, Tony Jaa, JuJu Chan, Marie Avgeropoulos, Rick Yune, Eddie Steeples, James P. Bennett, Dan Rizzuto, Ryan Tarran, John D. Hickman, Tommy Walker",
            "Izabela Rose, Siena Agudong, Kyle Howard, Max Torina, Elie Samouhi, Alison Fernandez, Vicki Lewis, Cynthia Kaye McWilliams, Jaime M. Callica, Callum Seagram Airlie, Amitai Marmorstein, Elaine Kao, Emily Delahunty, Ricardo Ortiz, Jason Asuncion, Yasmeen Fletcher, Melody Nosipho Niemann,Lou Ticzon, Valencia Budijanto, Josh Zaharia, Esther Li, Yoko Misawa, Rosalba Perez, Leslie Dos Remedios ",
            "Mel Gibson, Walton Goggins, Marianne Jean-Baptiste, Shaun Benson, Paulino Nunes, Chance Hurstfield, Michelle Lang, Deborah Grover, Michael Dickson",
            "John David Washington, Robert Pattinson, Elizabeth Debicki, Kenneth Branagh, Dimple Kapadia, Himesh Patel, Aaron Taylor-Johnson, Michael Caine, Clémence Poésy, Martin Donovan",
            "William Adams, Jezibell Anat, Gunner Bridger, Meghan Bridgers, Jerry Chesser, Alan Cope II, Judy DeLoach, William DeLoach",
            "Bruce Willis, Jesse Metcalfe, Natalie Eva Marie, Lala Kent, Texas Battle, Swen Temmel, Sergio Rizzuto, Tyler Jon Olson, Jon Galanis",
            "Liu Yifei, Jet Li, Tzi Ma, Donnie Yen, Gong Li, Jason Scott Lee, Yoson An, Rosalind Chao, Cheng Pei-Pei",
            "Lannick Gautry,Stanislas Merhar, Kaaris, Jean Reno, David Belle,　Gérard Lanvin,　Moussa Maaskri,　Catherine Marchal,　Francis Renaud,　Erika Sainte,　Barbara Opsomer,　Ambre Pietri,　",
            "Gerard Butler,　Morena Baccarin,　David Denman,　Hope Davis,　Roger Dale Floyd,　Scott Glenn,　Andrew Bachelor,　Merrin Dungey,　Holt McCallany,　Gary Weeks,　Tracey Bonner,　Joshua Mikel,　Cate Jones,　Mike Gassaway,　Anissa Matlock",
            "Bella Thorne, Malin Åkerman, Alec Baldwin, Dulcé Sloan, Mariana Paola Vicente, Vitoria Setta, Julie Michaels, Nicol Paone, Alexia Barlier, Fortune Feimster, Marissa Labog, Julia Sandstrom",
            "Maisie Williams, Anya Taylor-Joy, Charlie Heaton,　Alice Braga,　Blu Hunt,　Henry Zaga,　Adam Beach,　Thomas Kee,　Colbi Gannett,　Happy Anderson,　Dustin Ceithamer,　Mickey Gilmore,　Jeffrey Corazzini,　Jacinto Vega SpiritWolf,　Chuck,　Marilyn Manson",
            "Adam Copeland,　Kelsey Grammer,　Thomas Jane,　Denise Richards,　Katrina Norman,　Patrick Lamont Jr.,　Andrew Lawrence,　Joey Lawrence,　Matthew Lawrence,　Al Sapienza,　Aleksander Vayshelboym,　Jolene Kim,　Candi Brooks,　Tom DeNucci,　Bryan McClure",
            "Millie Bobby Brown,　Henry Cavill,　Sam Claflin,　Helena Bonham Carter,　Louis Partridge,　Adeel Akhtar,　Fiona Shaw,　Frances de la Tour,　Burn Gorman,　Susan Wokoma,　Claire Rushbrook,　David Bamber,　Hattie Morahan,　Gaby French,　Paul Copley,　Ellie Haddington,　Alex Kelly,　James Duke,　Connor Catchpole",
            "Kang Dong-won,　Lee Jung-hyun,　Lee Re,　Kwon Hae-hyo,　Kim Min-jae,　Koo Kyo-hwan,　Kim Do-yoon,　Lee Ye-won,　Kim Gyu-baek,　Jang So-yeon,　Daniel Joey Albright,　Hwang Yeon-hui,　Cha Si-won,　Pierce Conran",
            "Anne Hathaway,　Octavia Spencer,　Stanley Tucci,　Jahzir Bruno,　Chris Rock,　Codie-Lei Eastick,　Kristin Chenoweth,　Brian Bovell,　Charles Edwards,　Morgana Robinson,　Josette Simon,　Eugenia Caruso,　Ana Maria Maskell,　Orla O'Rourke,　Penny Lisle,　Simon Manyonda,　Amber Flanagan,　Jonathan Livingstone,　Philippe Spall,　Eurydice El-Etr",
            "Natsuki Hanae, Akari Kitō, Hiro Shimono, Yoshitsugu Matsuoka, Satoshi Hino, Takahiro Sakurai, Katsuyuki Konishi, Saori Hayami, Kenichi Suzumura, Tomokazu Seki, Tomokazu Sugita, Toshiyuki Morikawa, Rina Satou, Shin-ichiro Miki, Houko Kuwashima, Kaede Hondo, You Taichi, Konomi Kohara, Aoi Koga, Rikiya Koyama",
            "Vince Vaughn,　Kathryn Newton,　Alan Ruck,　Katie Finneran,　Celeste O'Connor,　Misha Osherovich,　Uriah Shelton,　Dana Drori,　Dustin Lewis,　Kelly Lamor Wilson,　Melissa Collazo,　Nick Arapoglou,　Radhesh Aria,　Emily Holder,　Nicholas Stargel,　Mitchell Hoog,　Jennifer Pierce Mathus,　Uriah Shelton,　Zack Shires,　Magnus Diehl",
            "Jessica Chastain,　John Malkovich,　Colin Farrell,　Common,　Geena Davis,　Ioan Gruffudd,　Joan Chen,　Jess Weixler,　Diana Silvers,　Falk Hentschel, Lin Hultgren, Michael Guarnera, Joe Sobalo Jr., Efka Kvaraciejus, Michel Muller, Brian Tobin, Alexandria Tait, Uliana Tabaka, Yefim Somin, Susan Halsey Singer, Scott Sederquist",
            "Paulo Americano, Terence Bridgett, Tamer Burjaq, Nompilo Gwala, Paul Hampshire, Dale Jackson, Hakeem Kae-Kazim, Terri Lane, Robin Minifie, Raúl Rosário, Rapulana Seiphemo, Jenna Upton, Neide Vieira",
            "Megan Fox, Philip Winchester, Greg Kriek, Brandon Auret, Jessica Sutton, Kenneth Fok, Isabel Bassett, Adam Deacon, Sisanda Henna, Tamer Burjaq, Ashish Gangapersad, Calli Taylor, Lee-Anne Liebenberg"
    )
    val screenplay = arrayOf(
            "Marie Avgeropoulos, Rick Yune",
            "Nick Pustay",
            "Eshom Nelms, Ian Nelms",
            "Kenneth Branagh, Dimple Kapadia",
            "Christopher Forbes",
            "Joe Russo, Chris LaMont, Clayton Haugen, Nikolai From",
            "Rick Jaffa, Amanda Silver, Lauren Hynek, Elizabeth Martin, Amanda Silver",
            "Arnaud Putman, Jimena Esteve",
            "Dana Gonzales,　Clay A. Griffith",
            "Joseph Downey",
            "Knate Gwaltney,　Dave Cockrum,　Len Wein",
            "Andrew Lawrence,　Tim Schaaf",
            "Jack Thorne",
            "Yeon Sang-ho,　Lee Mok-won,　Park Jun-yong,　Yu Cheong",
            "Robert Zemeckis,　Kenya Barris, Guillermo del Toro",
            "Yūta Kiso, Yōko Kajiyama, Kōji Etō, Akane Okabe, Kazuki Nishiwaki",
            "Christopher Landon,Ben Baudhuin,　Laurie Rose",
            "Matthew Newton",
            "Maradona Dias Dos Santos,　Chris Roland",
            "M.J. Bassett, Isabel Bassett"
    )
    val writer = arrayOf(
            "Dimitri Logothetis, Jim McGrath",
            "Nick Pustay",
            "Eshom Nelms, Ian Nelms",
            "Christopher Nolan",
            "Micah Lyons",
            "Joe Russo, Chris LaMont, Clayton Haugen, Nikolai From",
            "Rick Jaffa, Amanda Silver, Lauren Hynek, Elizabeth Martin, Amanda Silver",
            "Olivier Marchal",
            "Chris Sparling",
            "Joseph Downey, Hope Bryant",
            "Josh Boone, Knate Lee",
            "Tyler W. Konney, Richard Switzer",
            "Nancy Springer",
            "Yeon Sang-ho,　Ryu Yong-jae",
            "Roald Dahl",
            "Takahiro Miura, Haruo Sotozaki, Koyoharu Gotōge",
            "Christopher Landon, Michael Kennedy",
            "Matthew Newton",
            "Maradona Dias Dos Santos,　Chris Roland",
            "M.J. Bassett, Isabel Bassett"
    )
    val director = arrayOf(
            "Dimitri Logothetis",
            "Joe Nussbaum",
            "Eshom Nelms, Ian Nelms",
            "Christopher Nolan",
            "Christopher Forbes",
            "Matt Eskandari",
            "Niki Caro",
            "Olivier Marchal",
            "Ric Roman Waugh",
            "Paul Leyden",
            "Josh Boone",
            "Andrew Lawrence",
            "Harry Bradbeer",
            "Yeon Sang-ho",
            "Robert Zemeckis",
            "Haruo Sotozaki",
            "Christopher Landon",
            "Tate Taylor",
            "Maradona Dias Dos Santos,　Chris Roland",
            "M.J. Bassett"
    )
    val titleMovies = arrayOf(
            "Jiu Jitsu (2020)",
            "Upside-Down Magic (2020)",
            "Fatman (2020)",
            "Tenet (2020)",
            "The Dalton Gang (2020)",
            "Hard Kill (2020)",
            "Mulan (2020)",
            "Rogue City (2020)",
            "Greenland (2020)",
            "Chick Fight (2020)",
            "The New Mutants (2020)",
            "Money Plane (2020)",
            "Enola Holmes (2020)",
            "Peninsula (2020)",
            "Roald Dahl's The Witches (2020)",
            "Demon Slayer the Movie: Mugen Train (2020)",
            "Freaky (2020)",
            "Ava (2020)",
            "Santana (2020)",
            "Rogue (2020)"
    )
     val posterMovies = arrayOf(
            "https://image.tmdb.org/t/p/w220_and_h330_face/eLT8Cu357VOwBVTitkmlDEg32Fs.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/xfYMQNApIIh8KhpNVtG1XRz0ZAp.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/4n8QNNdk4BOX9Dslfbz5Dy6j1HK.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/6OeGqp18oZucUGziMIRNhLouZ75.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/ugZW8ocsrfgI95pnQ7wrmKDxIe.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/9HT9982bzgN5on1sLRmc1GMn6ZC.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/4ZocdxnOO6q2UbdKye2wgofLFhB.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/xrI4EnZWftpo1B7tTvlMUXVOikd.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/6CoRTJTmijhBLJTUNoVSUNxZMEI.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/riYInlsq2kf1AWoGm80JQW5dLKp.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/sy6DvAu72kjoseZEjocnm2ZZ09i.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/8xC6QSyxrpm0D5A6iyHNemEWBVe.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/9Rj8l6gElLpRL7Kj17iZhrT5Zuw.jpg",
            "https://image.tmdb.org/t/p/w220_and_h330_face/uOw5JD8IlD546feZ6oxbIjvN66P.jpg"


    )

     val overviewMovies =
            arrayOf(
                    "Every six years, an ancient order of jiu-jitsu fighters joins forces to battle a vicious race of alien invaders. But when a celebrated war hero goes down in defeat, the fate of the planet and mankind hangs in the balance.",
                    "Nory and her best friend Reina enter the Sage Academy for Magical Studies, where Nory’s unconventional powers land her in a class for those with wonky, or “upside-down,” magic. Undaunted, Nory sets out to prove that that upside-down magic can be just as powerful as right-side-up.",
                    "A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.",
                    "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                    "When their brother Frank is killed by an outlaw, brothers Bob Dalton, Emmett Dalton and Gray Dalton join their local sheriff's department. When they are cheated by the law, they turn to crime, robbing trains and anything else they can steal from over the course of two years in the early 1890's. Trying to out do Jesse James, they attempt to rob two banks at once in October of 1892, and things get ugly.",
                    "The work of billionaire tech CEO Donovan Chalmers is so valuable that he hires mercenaries to protect it, and a terrorist group kidnaps his daughter just to get it.",
                    "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.",
                    "Caught in the crosshairs of police corruption and Marseille’s warring gangs, a loyal cop must protect his squad by taking matters into his own hands.",
                    "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
                    "When Anna Wyncomb is introduced to an an underground, all-female fight club in order to turn the mess of her life around, she discovers she is much more personally connected to the history of the club than she could ever imagine.",
                    "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.",
                    "A professional thief with \$40 million in debt and his family's life on the line must commit one final heist - rob a futuristic airborne casino filled with the world's most dangerous criminals.",
                    "While searching for her missing mother, intrepid teen Enola Holmes uses her sleuthing skills to outsmart big brother Sherlock and help a runaway lord.",
                    "A soldier and his team battle hordes of post-apocalyptic zombies in the wastelands of the Korean Peninsula.",
                    "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
                    "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!.",
                    "A mystical, ancient dagger causes a notorious serial killer to magically switch bodies with a 17-year-old girl.",
                    "A black ops assassin is forced to fight for her own survival after a job goes.",
                    "Two brothers — one a narcotics agent and the other a general — finally discover the identity of the drug lord who murdered their parents decades ago. They may kill each other before capturing the bad guys.",
                    "Battle-hardened O’Hara leads a lively mercenary team of soldiers on a daring mission: rescue hostages from their captors in remote Africa. But as the mission goes awry and the team is stranded, O’Hara’s squad must face a bloody, brutal encounter with a gang of rebels."
            )
}